import type { MediaRecord } from "@/content/types"

// Source-linked content snapshot. User-requested assets do not imply a license grant.
export const mediaItems: MediaRecord[] = [
  {
    "id": "media-ig-academy",
    "slug": "instagram-atlas-performans",
    "title": "@atlas_performans",
    "brand": "academy",
    "platform": "instagram",
    "postUrl": "https://www.instagram.com/atlas_performans/",
    "type": "embed",
    "captionSummary": "Atlas Performans Akademisi",
    "permissionStatus": "embedded",
    "featured": true,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Atlas Performans Akademisi Instagram",
    "sourceUrl": "https://www.instagram.com/atlas_performans/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05"
  },
  {
    "id": "media-ig-theatre",
    "slug": "instagram-atlas-tiyatro",
    "title": "@atlastiyatro",
    "brand": "theatre",
    "platform": "instagram",
    "postUrl": "https://www.instagram.com/atlastiyatro/",
    "type": "embed",
    "captionSummary": "Atlas Tiyatro Araştırmaları",
    "permissionStatus": "embedded",
    "featured": true,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Atlas Tiyatro Instagram",
    "sourceUrl": "https://www.instagram.com/atlastiyatro/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05"
  },
  {
    "id": "media-ig-seeinglab",
    "slug": "instagram-seeing-lab",
    "title": "@seeinglab",
    "brand": "academy",
    "platform": "instagram",
    "postUrl": "https://www.instagram.com/seeinglab/",
    "type": "embed",
    "captionSummary": "Seeing Lab",
    "permissionStatus": "embedded",
    "featured": true,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Seeing Lab Instagram",
    "sourceUrl": "https://www.instagram.com/seeinglab/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05"
  },
  {
    "id": "media-dublor-g-1",
    "slug": "dublor-galeri-1",
    "title": "Dublörün Dilemması — galeri 1",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": true,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g1.jpg",
      "alt": "Dublörün Dilemması 1",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-g-2",
    "slug": "dublor-galeri-2",
    "title": "Dublörün Dilemması — galeri 2",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": true,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g2.jpg",
      "alt": "Dublörün Dilemması 2",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-g-3",
    "slug": "dublor-galeri-3",
    "title": "Dublörün Dilemması — galeri 3",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": true,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g3.jpg",
      "alt": "Dublörün Dilemması 3",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-g-4",
    "slug": "dublor-galeri-4",
    "title": "Dublörün Dilemması — galeri 4",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": true,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g4.jpg",
      "alt": "Dublörün Dilemması 4",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-g-5",
    "slug": "dublor-galeri-5",
    "title": "Dublörün Dilemması — galeri 5",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g5.jpg",
      "alt": "Dublörün Dilemması 5",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-g-6",
    "slug": "dublor-galeri-6",
    "title": "Dublörün Dilemması — galeri 6",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g6.jpg",
      "alt": "Dublörün Dilemması 6",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-g-7",
    "slug": "dublor-galeri-7",
    "title": "Dublörün Dilemması — galeri 7",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g7.jpg",
      "alt": "Dublörün Dilemması 7",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-g-8",
    "slug": "dublor-galeri-8",
    "title": "Dublörün Dilemması — galeri 8",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g8.jpg",
      "alt": "Dublörün Dilemması 8",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-g-9",
    "slug": "dublor-galeri-9",
    "title": "Dublörün Dilemması — galeri 9",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Sahne galerisi — tiyatrolar.com.tr",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublorun-gallery/g9.jpg",
      "alt": "Dublörün Dilemması 9",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-all-30569",
    "slug": "dublor-all-30569",
    "title": "Dublörün Dilemması — kare 9",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/",
    "type": "image",
    "captionSummary": "Promosyon arşivi",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublor-all/g30569.jpg",
      "alt": "Dublörün Dilemması 30569",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-to-6",
    "slug": "dublor-to-6",
    "title": "Dublörün Dilemması — tiyatronline 6",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatronline.com/oyunlar/dublorun-dilemmasi-14930",
    "type": "image",
    "captionSummary": "Tiyatro Online arşivi",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatro Online: Dublörün Dilemması",
    "sourceUrl": "https://tiyatronline.com/oyunlar/dublorun-dilemmasi-14930",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublor-to/full-6.jpg",
      "alt": "Dublörün Dilemması TO 6",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-to-8",
    "slug": "dublor-to-8",
    "title": "Dublörün Dilemması — tiyatronline 8",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatronline.com/oyunlar/dublorun-dilemmasi-14930",
    "type": "image",
    "captionSummary": "Tiyatro Online arşivi",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatro Online: Dublörün Dilemması",
    "sourceUrl": "https://tiyatronline.com/oyunlar/dublorun-dilemmasi-14930",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublor-to/full-8.jpg",
      "alt": "Dublörün Dilemması TO 8",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-dublor-to-9",
    "slug": "dublor-to-9",
    "title": "Dublörün Dilemması — tiyatronline 9",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatronline.com/oyunlar/dublorun-dilemmasi-14930",
    "type": "image",
    "captionSummary": "Tiyatro Online arşivi",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": true,
    "sourceName": "Tiyatro Online: Dublörün Dilemması",
    "sourceUrl": "https://tiyatronline.com/oyunlar/dublorun-dilemmasi-14930",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/dublor-to/full-9.jpg",
      "alt": "Dublörün Dilemması TO 9",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-sezuan-1",
    "slug": "sezuan-1",
    "title": "Sezuan’ın İyi İnsanı — 1",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatronline.com/oyunlar/sezuan-in-yi-nsani-13905",
    "type": "image",
    "captionSummary": "Sezuan arşivi",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": false,
    "sourceName": "Tiyatro Online: Sezuan’ın İyi İnsanı",
    "sourceUrl": "https://tiyatronline.com/oyunlar/sezuan-in-yi-nsani-13905",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/sezuan/scene-01.jpg",
      "alt": "Sezuan 1",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-sezuan-2",
    "slug": "sezuan-2",
    "title": "Sezuan’ın İyi İnsanı — 2",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatronline.com/oyunlar/sezuan-in-yi-nsani-13905",
    "type": "image",
    "captionSummary": "Sezuan arşivi",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": false,
    "sourceName": "Tiyatro Online: Sezuan’ın İyi İnsanı",
    "sourceUrl": "https://tiyatronline.com/oyunlar/sezuan-in-yi-nsani-13905",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/sezuan/scene-02.jpg",
      "alt": "Sezuan 2",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-sezuan-3",
    "slug": "sezuan-3",
    "title": "Sezuan’ın İyi İnsanı — 3",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatronline.com/oyunlar/sezuan-in-yi-nsani-13905",
    "type": "image",
    "captionSummary": "Sezuan arşivi",
    "permissionStatus": "licensed",
    "featured": false,
    "status": "verified",
    "isCurrent": false,
    "sourceName": "Tiyatro Online: Sezuan’ın İyi İnsanı",
    "sourceUrl": "https://tiyatronline.com/oyunlar/sezuan-in-yi-nsani-13905",
    "verifiedAt": "2026-08-05",
    "lastUpdatedAt": "2026-08-05",
    "thumbnail": {
      "src": "/media/theatre/sezuan/scene-03.jpg",
      "alt": "Sezuan 3",
      "permissionStatus": "licensed",
      "owner": "Atlas Tiyatro",
      "retrievedAt": "2026-08-05"
    }
  },
  {
    "id": "media-sezuanin-iyi-insani-scene-2",
    "slug": "sezuanin-iyi-insani-scene-2",
    "title": "Sezuan’ın İyi İnsanı — sahneden",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/tiyatro/sezuanin-iyi-insani",
    "type": "image",
    "permissionStatus": "userRequested",
    "featured": false,
    "status": "verified",
    "isCurrent": false,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/tiyatro/sezuanin-iyi-insani",
    "verifiedAt": "2026-09-06",
    "lastUpdatedAt": "2026-09-06",
    "thumbnail": {
      "src": "/media/theatre/sezuanin-iyi-insani/sezuanin-iyi-insani-scene-2.jpg",
      "alt": "Sezuan’ın İyi İnsanı — sahne fotoğrafı",
      "originalUrl": "https://tiyatrolar.com.tr/files/activity/s/sezuanin-iyi-insani/gallery/26600/sezuanin-iyi-insani-26600.jpg",
      "permissionStatus": "userRequested",
      "retrievedAt": "2026-09-06"
    }
  },
  {
    "id": "media-uysal-kadin-scene-2",
    "slug": "uysal-kadin-scene-2",
    "title": "Uysal Kadın — sahneden",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/tiyatro/uysal-kadin",
    "type": "image",
    "permissionStatus": "userRequested",
    "featured": false,
    "status": "verified",
    "isCurrent": false,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/tiyatro/uysal-kadin",
    "verifiedAt": "2026-09-06",
    "lastUpdatedAt": "2026-09-06",
    "thumbnail": {
      "src": "/media/theatre/uysal-kadin/uysal-kadin-scene-2.jpg",
      "alt": "Uysal Kadın — sahne fotoğrafı",
      "originalUrl": "https://tiyatrolar.com.tr/files/activity/u/uysal-kadin/gallery/23784/uysal-kadin-23784.jpg",
      "permissionStatus": "userRequested",
      "retrievedAt": "2026-09-06"
    }
  },
  {
    "id": "media-yabanci-scene-2",
    "slug": "yabanci-scene-2",
    "title": "Yabancı — sahneden",
    "brand": "theatre",
    "platform": "local",
    "postUrl": "https://tiyatrolar.com.tr/tiyatro/yabanci",
    "type": "image",
    "permissionStatus": "userRequested",
    "featured": false,
    "status": "verified",
    "isCurrent": false,
    "sourceName": "Tiyatrolar.com.tr",
    "sourceUrl": "https://tiyatrolar.com.tr/tiyatro/yabanci",
    "verifiedAt": "2026-09-06",
    "lastUpdatedAt": "2026-09-06",
    "thumbnail": {
      "src": "/media/theatre/yabanci/yabanci-scene-2.jpg",
      "alt": "Yabancı — sahne fotoğrafı",
      "originalUrl": "https://tiyatrolar.com.tr/files/activity/y/yabanci/gallery/20747/yabanci-20747.jpg",
      "permissionStatus": "userRequested",
      "retrievedAt": "2026-09-06"
    }
  },
]
