import { CONTENT_RESEARCH_DATE } from "@/content/sources"
import type { ReviewRecord } from "@/content/types"

/** İzleyici yorumları — https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi */
export const reviews: ReviewRecord[] = [
  {
    id: "review-dublor-01",
    slug: "dublor-yorum-1",
    title: "Buse S. — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Sergilenen oyun, prodüksiyon kalitesi ve sahneleme başarısıyla gerçekten etkileyiciydi. Tüm ekibi bu kolektif başarıdan dolayı tebrik ederim. Özellikle Müge Hanım’ın sahne hakimiyeti, karakterin derinliğini yansıtmadaki ustalığı ve yüksek enerjisi oyunun etkileyiciliğini bambaşka bir seviyeye taşımış. Başarılarınızın devamını dilerim.",
    shortDescription: "Buse S.",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-02",
    slug: "dublor-yorum-2",
    title: "Bedirhan Bedirhan — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Kitabı üniversite yıllarımda okumuş çok sevmiştim, o kadar merak ettim ki nasıl sahneleyecekler diye. O kadar sevdim ki anlatamam. Kan ter içinde kaldılar, o güzelim emeklerinizi izlediğim için mutlu hissettim. Herkese tavsiye ediyorum, oyun tam benlikti ta Beylikdüzü'nden sırf bu oyun için gittim iyi ki gitmişim. Oyuncular da ayrıca çok sevimli insanlar, çok emek verilmiş ilmek ilmek her sahne işlenmiş. Uzun zaman sonra oyuncuların ne dediğini t",
    shortDescription: "Bedirhan Bedirhan",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-03",
    slug: "dublor-yorum-3",
    title: "Rümeysa Günay — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Uzun zamandır bir oyunda bu kadar güldüğümü hatırlamıyorum. Oyuncuların hepsi ayrı ayrı çok iyiydi. Bu ekibi başka oyunlarda da tekrar Bursa’da görmeyi çok isterim.",
    shortDescription: "Rümeysa Günay",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-04",
    slug: "dublor-yorum-4",
    title: "Zeynep Külünkoğlu — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Birbirinden yetenekli isimler sebebiyle oyun boyunca favori karakterinizi seçmekte zorlanıyorsunuz. Yer yer güldüren bu oyunda, artılarıyla eksileriyle olması gerektiği gibi 'insan'lara ve samimi itiraflara şahit oluyorsunuz. Çok kolay abartıya kaçabilecek sahneleri ustalıkla karakterlere sempati uyandıracak şekilde işlemek ayrı bi meziyet.",
    shortDescription: "Zeynep Külünkoğlu",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-05",
    slug: "dublor-yorum-5",
    title: "Feyzanur Ülger — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Murat Menteş'in kitaplarını çok seven ve oyunun Ankaraya gelmesini dört gözle bekleyen birii olarak oyun beni çok mutlu etti. Salondan mutlu ayrıldım. Uyarlama gerçekten çok güzel olmuş. Oyunculuklar, sahne tasarımı, metni, oyunun ritmi çok memnun ediciydi. Kitabın en temel olgusu Nuh Tufanın albinoluğu, oyuncuya bir kaç beyaz dokunuşla aksettirilmeye çalışılmış. tamamen beyaz makyaj ve mavi lensle halledilemez miydi, diye düşündüm. tek eksiği o ",
    shortDescription: "Feyzanur Ülger",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-06",
    slug: "dublor-yorum-6",
    title: "Şevval Akbulut — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Moda sahnede izledik, son zamanlarda izlediğim en keyifli, akıcı oyundu. Romanını da çok beğenerek okumuştum. Oyunculuklar harikaydı açıkçası. Roman çok da güzel aktarılmış sahneye. Emeğinize sağlık...",
    shortDescription: "Şevval Akbulut",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-07",
    slug: "dublor-yorum-7",
    title: "Mert Baran — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Biz oyunu Alan Kadıköy de izledik ancak yazabiliyorum. Çok beğendik, akış çok güzel ilerledi. Hiç kopmadık. Oyunculuklar çok iyiydi. Bence oyun izlenmeye değer. Çıkın çıkın gidin.",
    shortDescription: "Mert Baran",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-08",
    slug: "dublor-yorum-8",
    title: "Anıl Selçuk — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunu bugün arkadaşlarim ile beraber Baba sahnede izledik. Oyuncuların farklı farklı karakterleri oynaması eleştirilmiş, biz bu durumun oyuna dinamiklik kattığını düşündük ve oldukça eğlenceli bulduk. Özellikle Ferruh karakterine çok güldük, kesinlikle tavsiye ediyorum.",
    shortDescription: "Anıl Selçuk",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-09",
    slug: "dublor-yorum-9",
    title: "Nülüfer Aklın — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunu prömiyerde izledim ve çok keyif aldım. Oyuncuların hepsi son derece başarılıydı. Özellikle İbrahim Kurban karakterini canlandıran ve daha önce birkaç oyunda izlediğim Tekin Ezgütekin yine çok etkileyici bir performans sergiledi. Başarılı bir uyarlama olmuş. Koltuklardaki not kartları da ince düşünülmüş bir detaydı. Tüm ekibi kutluyor, alkışınız bol olsun diyorum.",
    shortDescription: "Nülüfer Aklın",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-10",
    slug: "dublor-yorum-10",
    title: "Begum Celik — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunu geçtiğimiz hafta sonu Ses Tiyatrosu’nda izledim. Uzun zaman sonra zevkle izlediğimiz bir oyun oldu. Cok keyifli bir oyun. Harika bir sezon ve alkisi bol olsun✨",
    shortDescription: "Begum Celik",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-11",
    slug: "dublor-yorum-11",
    title: "Zehra Çelik — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Kitabı çok severek okumuş biri olarak oyundan da beklentim hayli yüksekti. Baba Sahne'de izlediğim oyun, oyuncular, müzikler, dekor tam anlamıyla beklentimi karşıladı. Başından sonuna zevkle izledim oyunu. Cast seçimi çok doğru. Oyuncuların hepsi karakterlerine çok çok yakışmış. Kitap karşımdaydı diyebilirim. İkinci defa izlemeyi düşündüğüm bu oyunu tiyatro severlerin de kaçırmamasını öneririm. Tüm ekibin emeklerine sağlık.",
    shortDescription: "Zehra Çelik",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-12",
    slug: "dublor-yorum-12",
    title: "Yezdan Atılgan — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Murat Menteş hayranı olarak, kitaplarını okurken aldığım tadı bu oyunda da aldığımı söyleyebilirim. İnanılmaz güzel uyarlanmış bir oyun. Müzikler, \"sayın seyirci\" diye arada bizimle de konuşulması, arada verilen bilgiler hepsi o kadar uyumlu ve yerindeydi ki. Ayrıca oyuncuların hepsi rollerine inanılmaz yakışmış. Tekrar tekrar izlemek isteyeceğim ve herkese büyük bir istekle tavsiye edeceğim bir oyun olarak listemde yerini almıştır. Emeği geçen h",
    shortDescription: "Yezdan Atılgan",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-13",
    slug: "dublor-yorum-13",
    title: "Yaprak Demir — izleyici yorumu",
    kind: "critique",
    rating: 10,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunu bu akşam Dasdas'da izleme fırsatı buldum, normalde izlediğim oyunlarla ilgili yorum yazmaya üşenirim ancak bu oyun için kendimi bir şeyler yazmak zorunda hissettim. Romanı okumadım ancak güzel bir oyun izlediğimi söyleyebilirim ama şahsi fikrim oyuncuların performansının oyunun kendisinden daha etkileyici olduğu. Özellikle Tekin Ezgütekin'in yarattığı karakterler ve dahada önemlisi karakterler arasındaki geçişi takdire şayan. Ediz Akşehir v",
    shortDescription: "Yaprak Demir",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-14",
    slug: "dublor-yorum-14",
    title: "Ozan İnce — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Romanı tiyatroya uyarlamak pek kolay olmayabiliyor fakat hiç fena olmayan bir uyarlama olmuş. Kitabı çok severek okumuştum ve onun merakıyla gittim, yaratılan dünya hoşuma gitti, oyunun temposu çok kararında. Keyifli bir oyundu",
    shortDescription: "Ozan İnce",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-15",
    slug: "dublor-yorum-15",
    title: "Veli Seven — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "İbb Kültür sayesinde Tuzla İdris Güllüce Kültür Merkezinde izleme şansı bulduk. Metin bence güzeldi. Vermek istediği mesaj netti. Oyuncular da çok başarılıydı. Özellikle Tekin Ezgütekin'i çok başarılı buldum. Keyifli bir akşam geçirdim. İzlemenizi tavsiye ederim.",
    shortDescription: "Veli Seven",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-16",
    slug: "dublor-yorum-16",
    title: "Tukaka Sanat — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "\"Dublörün Dilemması\", zekice kurgusu, sürükleyici temposu ve ince mizahı ile sahnede gerçek bir enerji patlaması yaratıyor. Oyun, yalnızca hikayesiyle değil, oyuncuların sahici performanslarıyla da etkileyici bir bütünlük kuruyor. Her oyuncu karakterine güçlü bir dinamizm katarken, özellikle diyaloglar arasındaki geçişler hem ritmini kaybetmiyor hem de izleyicinin dikkatini hep canlı tutuyor. Sahne tasarımı, minimal unsurlar kullanmasına rağmen h",
    shortDescription: "Tukaka Sanat",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-17",
    slug: "dublor-yorum-17",
    title: "Tiyatro Günlüklerim — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "“Aynı Anda İki Yerde Birden Olmanız Mı Gerekiyor!” “Bizi Arayın!” Bilkent Sahne’de uzun zamandır bir oyunun bu kadar kalabalık olduğuna şahit olmamıştık. Ankara seyircisi bilinçli bir seyirci olduğunu ve kaliteli yapımları izlemeyi tercih ettiğini bir kez daha bizlere göstermiş oldu. Murat Menteş’in kitaplarında yarattığı dünyayı severek takip ettiğimiz için “Dublörün Dilemması” nın sahneye uyarlanmasını çok ama çok başarılı bulduğumuzu belirtmel",
    shortDescription: "Tiyatro Günlüklerim",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-18",
    slug: "dublor-yorum-18",
    title: "Sibel Açıkalın — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "İşte absurd tiyatro budur. Abdurrahman Merallı, Çetin Kaya,Tekin Ezgütekin nasıl bir oyunculuktu, mimikler sanki animasyon karakteri gibi inanılmaz güçlü idi. Alkışınız bol olsun.",
    shortDescription: "Sibel Açıkalın",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-19",
    slug: "dublor-yorum-19",
    title: "Anil Micik — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunu ses tiyatrosunda izledim , kitabı daha önce okumuş biri olarak acaba nasıl sahneye taşıyacaklarını çok merak ediyordum. Bence hem yönetmen hemde oyuncular bu işin altından çok güzel kalkmışlar. Güzel akıcı şahane bir oyun izlettiler bize. Kitabın yazarı olan sayın Murat Menteşe de bir alkışı burdan iletelim. Seyircisi ve alkışı bol olsun bu güzel oyununda",
    shortDescription: "Anil Micik",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-20",
    slug: "dublor-yorum-20",
    title: "Nilay T. — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Konusunu, senaryoyu bir kenara bırak, seyir zevki yüksek bir oyun. Sadece bu bile yeterli oyuna gitmek için.",
    shortDescription: "Nilay T.",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-21",
    slug: "dublor-yorum-21",
    title: "Özgür Eliçevik — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunculuklar ve sahnelenişi gayet güzeldi. İzlerken keyif aldım ve hiç sıkılmadım. Kitabını okumamıştım ama oyunu cidden eğlenceli. İzlemenizi tavsiye ederim ✨",
    shortDescription: "Özgür Eliçevik",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-22",
    slug: "dublor-yorum-22",
    title: "Derya Dilege — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunu dün Moda Sahnesi'nde izledim. Kitabı okumadığım için herhangi bi' beklentim yoktu. İlk dakikasından son dakikasına kadar çok keyif aldığım bi' oyundu. Çoğu yerinde zekice yazılmış sarkastik diyaloglara kahkaha atarak, yer yer de duygulandığım bir oyun oldu. Kimlik çatışması ve günlük hayatta takmak zorunda olduğumuz maskelerin yarattığı ilüzyona konu olarak takık olduğum için bi' ayrı hoşuma gitti. Yönetmen Sercan Özinan tüm oyun boyunca sı",
    shortDescription: "Derya Dilege",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-23",
    slug: "dublor-yorum-23",
    title: "Cenk Kayacan — izleyici yorumu",
    kind: "critique",
    rating: 9,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunu dün DasDas'ta izledim. Sezonun en dikkat çekici oyunlarından olacağı kanısındayım. Murat Menteş dünyasına az da olsa hakim birisiyim ama romanı okumamıştım. Oyun dinamik, eğlenceli ve bir o kadar değişik. Romanı bilmememe rağmen akıcı bir oyun gibi izledim. Oyunculuklar gayet iyi ama Ediz Akşehir'e ayrı parantez açmak gerekir. Başından sonuna kadar sahnede ve maske ile olan oyunculuğu gerçekleştimek ayrı bir efor ve meziyet gerektiriyor. Te",
    shortDescription: "Cenk Kayacan",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
  {
    id: "review-dublor-24",
    slug: "dublor-yorum-24",
    title: "Hatice Kurt — izleyici yorumu",
    kind: "critique",
    rating: 8,
    ratingMax: 10,
    subjectId: "prod-dublorun-dilemmasi",
    subjectType: "production",
    summary: "Oyunculuklar muhteşem. Özellikle Tekin Ezgütekini izlemek çok keyifli.",
    shortDescription: "Hatice Kurt",
    status: "verified",
    isCurrent: true,
    sourceName: "Tiyatrolar.com.tr",
    sourceUrl: "https://tiyatrolar.com.tr/tiyatro/dublorun-dilemmasi",
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
  },
]
