import { CONTENT_RESEARCH_DATE, sources } from "@/content/sources"
import type { ProgramRecord } from "@/content/types"

/**
 * Schedule details from Instagram (Temel Oyunculuk / Müzikal Tiyatro)
 * are not published as verified here until caption text is directly confirmed.
 */
export const programs: ProgramRecord[] = [
  {
    id: "program-temel-oyunculuk",
    slug: "temel-oyunculuk-akademisi",
    title: "Temel Oyunculuk Akademisi",
    brand: "academy",
    category: "acting",
    shortDescription:
      "Uzun dönemli oyunculuk programı; akademinin çekirdek eğitim hattı.",
    fullDescription:
      "Atlas Performans Akademisi’nin oyunculuk odaklı uzun dönemli programıdır. Basın kaynaklarında eğitmen kadrosu Prof. Dr. Senem Cevher, Doç. Uluç Esen, Hasan Şahintürk, Dr. Ece Çelikçapa Özinan ve Dr. Sercan Özinan olarak geçer.",
    instructors: [
      "person-senem-cevher",
      "person-uluc-esen",
      "person-hasan-sahinturk",
      "person-ece-ozinan",
      "person-sercan-ozinan",
    ],
    applicationStatus: "unknown",
    goals: ["acting", "performance"],
    experienceLevel: "unknown",
    status: "verified",
    isCurrent: true,
    sourceName: sources.apaPress.name,
    sourceUrl: sources.apaPress.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    mediaPermissionStatus: "permissionRequired",
  },
  {
    id: "program-monolog",
    slug: "monolog-atolyesi",
    title: "Monolog Atölyesi",
    brand: "academy",
    category: "acting",
    shortDescription: "Monolog odaklı atölye çalışması.",
    fullDescription:
      "Basın kaynaklarına göre Monolog Atölyesi Dr. Ece Çelikçapa Özinan ile gerçekleştirilmiştir. Biletinial etkinlik sayfası araştırmada erişilemedi; güncel kontenjan ve tarih için kaynağı yeniden kontrol edin.",
    instructors: ["person-ece-ozinan"],
    applicationStatus: "completed",
    goals: ["acting"],
    status: "verified",
    isCurrent: false,
    sourceName: sources.apaPress.name,
    sourceUrl: sources.apaPress.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    ticketUrl: sources.monologWorkshop.url,
    additionalSources: [sources.monologWorkshop],
    mediaPermissionStatus: "permissionRequired",
  },
  {
    id: "program-audition-101",
    slug: "audition-101",
    title: "Rüzgâr Aksoy ile Audition 101",
    brand: "academy",
    category: "acting",
    shortDescription:
      "Kamera önü audition sunumu için örnek metinler üzerinden üç saatlik çalışma.",
    fullDescription:
      "Bu üç saatlik çalışma, örnek audition metinleri üzerinden yürütülür ve kamera önünde etkili audition sunumu için profesyonel stratejilere odaklanır. Katılımcılar metin analizi, karakter oluşturma ve kamera kullanımı tekniklerini çalışır. Kontenjan sınırlıdır. Biletinial kaydında etkinlik gerçekleşmiş görünür.",
    instructors: ["person-ruzgar-aksoy"],
    totalHours: 3,
    applicationStatus: "completed",
    format: "unknown",
    goals: ["acting", "cinema"],
    status: "verified",
    isCurrent: false,
    sourceName: sources.audition101.name,
    sourceUrl: sources.audition101.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    ticketUrl: sources.audition101.url,
    additionalSources: [sources.apaPress],
    mediaPermissionStatus: "permissionRequired",
  },
  {
    id: "program-senaryo",
    slug: "senaryo-yazarligi-atolyesi",
    title: "Senaryo Yazarlığı Atölyesi",
    brand: "academy",
    category: "writing",
    shortDescription:
      "Fikir geliştirmeden diyalog yazımına senaryo yazımının temel aşamaları.",
    fullDescription:
      "8 Aralık 2025’te başlayan, 4 hafta / 8 ders / 16 saat program. Yüz yüze: Çarşamba ve Cuma 19.00–21.00. Online: Pazartesi ve Perşembe 20.00–22.00. Online veya yüz yüze tercihli katılım. Biletinial kaydında etkinlik gerçekleşmiş görünür.",
    startDate: "2025-12-08",
    durationWeeks: 4,
    totalHours: 16,
    scheduleSummary:
      "Yüz yüze: Çarşamba & Cuma 19.00–21.00 · Online: Pazartesi & Perşembe 20.00–22.00",
    format: "hybrid",
    applicationStatus: "completed",
    goals: ["writing", "cinema"],
    status: "verified",
    isCurrent: false,
    sourceName: sources.screenwriting.name,
    sourceUrl: sources.screenwriting.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    ticketUrl: sources.screenwriting.url,
    contactPhone: "0545 392 12 72",
    mediaPermissionStatus: "permissionRequired",
  },
  {
    id: "program-kisa-film",
    slug: "fikirden-perdeye-kisa-film-atolyesi",
    title: "Fikirden Perdeye: Kısa Film Atölyesi",
    brand: "academy",
    category: "cinema",
    shortDescription:
      "Kısa film üretimini fikirden proje dosyasına ele alan uygulamalı atölye.",
    fullDescription:
      "8 Aralık 2025’te başlayan, 4 hafta / 8 ders / 16 saat program. Yüz yüze eğitim: Pazartesi ve Perşembe 19.00–21.00. Biletinial kaydında etkinlik gerçekleşmiş görünür.",
    startDate: "2025-12-08",
    durationWeeks: 4,
    totalHours: 16,
    scheduleSummary: "Pazartesi & Perşembe 19.00–21.00 (yüz yüze)",
    format: "in-person",
    applicationStatus: "completed",
    goals: ["cinema", "writing"],
    status: "verified",
    isCurrent: false,
    sourceName: sources.shortFilm.name,
    sourceUrl: sources.shortFilm.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    ticketUrl: sources.shortFilm.url,
    mediaPermissionStatus: "permissionRequired",
  },
  {
    id: "program-seeing-lab",
    slug: "seeing-lab",
    title: "Seeing Lab",
    brand: "academy",
    category: "lab",
    shortDescription:
      "Sinema odaklı film gösterimleri, yönetmen söyleşileri ve uygulamalı programlar.",
    fullDescription:
      "Akademi bünyesinde Doç. Dr. Deniz Telek’in koordinatörlüğünde faaliyet gösteren sinema laboratuvarı. Resmi Instagram: @seeinglab.",
    instructors: ["person-deniz-telek"],
    applicationStatus: "unknown",
    goals: ["cinema"],
    status: "verified",
    isCurrent: true,
    sourceName: sources.apaPress.name,
    sourceUrl: sources.apaPress.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    additionalSources: [sources.seeingLab],
    mediaPermissionStatus: "permissionRequired",
  },
  {
    id: "program-apa-talks",
    slug: "apa-talks",
    title: "APA Talks",
    brand: "academy",
    category: "talks",
    shortDescription:
      "Farklı disiplinlerden sanatçılar ve akademisyenlerle vodcast ve buluşma serisi planı.",
    fullDescription:
      "Basın kaynaklarında akademi etkinlik takviminde yer alacak vodcast serileri olarak geçer. Güncel bölüm listesi ve yayın tarihi bu araştırma anında doğrulanmamıştır.",
    applicationStatus: "unknown",
    status: "needsVerification",
    isCurrent: false,
    sourceName: sources.apaPress.name,
    sourceUrl: sources.apaPress.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    mediaPermissionStatus: "permissionRequired",
  },
  {
    id: "program-muzikal-tiyatro",
    slug: "muzikal-tiyatro-akademisi",
    title: "Müzikal Tiyatro Akademisi",
    brand: "academy",
    category: "musical",
    shortDescription:
      "Instagram kaynaklı program adı; haftalık/saat detayları doğrulanmayı bekliyor.",
    fullDescription:
      "Program adı kaynak listesinde yer alır; 14 hafta / 56 saat / dans-şarkı-oyunculuk gibi detaylar resmî Instagram açıklaması doğrudan doğrulanmadan kesinleştirilmemiştir.",
    applicationStatus: "unknown",
    goals: ["acting", "performance"],
    status: "needsVerification",
    isCurrent: false,
    sourceName: sources.academyInstagram.name,
    sourceUrl: sources.academyInstagram.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    mediaPermissionStatus: "permissionRequired",
  },
  {
    id: "program-barba-varley",
    slug: "eugenio-barba-julia-varley-masterclass",
    title: "Eugenio Barba ve Julia Varley Programı",
    brand: "academy",
    category: "masterclass",
    shortDescription:
      "19 Nisan’da Alan Kadıköy’de vokal dramaturji atölyesi ve özel masterclass.",
    fullDescription:
      "Atlas Performans Akademisi düzenlemesi. 09.30 Julia Varley “The Echo of Silence | Vokal Dramaturji Atölyesi”; 14.00 Eugenio Barba ve Julia Varley masterclass. Atölye başvuruları İngilizce motivasyon mektubu ile. Masterclass biletleri biletinial.com üzerinden. İletişim: info@atlasperformans.com. Haber tarihi 28 Mart 2026; etkinlik yılı haber metnindeki Nisan gününe bağlıdır.",
    startDate: "2026-04-19",
    scheduleSummary:
      "09.30 Vokal Dramaturji Atölyesi · 14.00 Özel Masterclass — Alan Kadıköy",
    format: "in-person",
    applicationStatus: "completed",
    goals: ["acting", "performance"],
    status: "verified",
    isCurrent: false,
    sourceName: sources.sahnedenBarba.name,
    sourceUrl: sources.sahnedenBarba.url,
    verifiedAt: CONTENT_RESEARCH_DATE,
    lastUpdatedAt: CONTENT_RESEARCH_DATE,
    contactPhone: undefined,
    mediaPermissionStatus: "permissionRequired",
  },
]
